# theme.py — Warna, ukuran font, border radius

# Warna utama (Tomat)
PRIMARY_COLOR = "#E05A4E"
PRIMARY_LIGHT = "#FF7B6E"
PRIMARY_DARK = "#B83A30"

# Warna background
BG_COLOR = "#1A1A2E"
BG_CARD = "#16213E"
BG_CARD_LIGHT = "#1E2D4A"

# Warna teks
TEXT_PRIMARY = "#FFFFFF"
TEXT_SECONDARY = "#A0A0B0"
TEXT_MUTED = "#6B6B7B"

# Warna mode
COLOR_POMODORO = "#E05A4E"
COLOR_SHORT_BREAK = "#4CAF50"
COLOR_LONG_BREAK = "#2196F3"

# Ukuran font
FONT_SIZE_TIMER = 48
FONT_SIZE_TITLE = 24
FONT_SIZE_SUBTITLE = 16
FONT_SIZE_BODY = 14
FONT_SIZE_SMALL = 12

# Border radius
BORDER_RADIUS_SM = 8
BORDER_RADIUS_MD = 12
BORDER_RADIUS_LG = 16
BORDER_RADIUS_XL = 24

# Ukuran timer lingkaran
TIMER_CIRCLE_SIZE = 250
TIMER_CIRCLE_STROKE = 8
TIMER_BG_STROKE = 4

# Shadow
SHADOW_OFFSET_X = 0
SHADOW_OFFSET_Y = 2
SHADOW_BLUR = 8
SHADOW_COLOR = "#40000000"
