name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Flet CLI and dependencies
        run: pip install flet flet-audio

      - name: Set up Java (diperlukan Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Tambahkan flag --yes agar otomatis mengizinkan instalasi Flutter SDK tanpa error EOF
      - name: Build APK
        run: flet build apk --yes --no-rich-output

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-apk
          # Path diperbaiki sesuai dengan standar folder output Flet
          path: build/apk/*.apk 
          retention-days: 7